import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testautomationpractice.blogspot.com/p/playwrightpractice.html#');
  await page.getByText('Username:').click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('user123@gmail.com');
  await page.getByRole('checkbox', { name: 'Accept terms' }).check();
  await page.getByRole('button', { name: 'Primary Action' }).click();
  await page.locator('#role-locators').getByRole('link', { name: 'Home' }).click();
  await page.getByText('colored text').click();
  await page.getByText('List item 1').click();
  await page.getByRole('button', { name: 'Submit Form' }).click();
  await page.getByRole('textbox', { name: 'Email Address:' }).click();
  await page.getByRole('textbox', { name: 'Email Address:' }).fill('usertest@gmail.com12');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('3@user');
  await page.getByRole('spinbutton', { name: 'Your Age:' }).click();
  await page.getByRole('spinbutton', { name: 'Your Age:' }).fill('34');
  await page.getByRole('radio', { name: 'Standard' }).check();
  await page.getByRole('textbox', { name: 'Enter your full name' }).click();
  await page.getByRole('textbox', { name: 'Enter your full name' }).click();
  await page.getByRole('textbox', { name: 'Enter your full name' }).fill('user test');
  await page.getByRole('textbox', { name: 'Phone number (xxx-xxx-xxxx)' }).click();
  await page.getByRole('textbox', { name: 'Phone number (xxx-xxx-xxxx)' }).fill('87623482736942w');
  await page.getByRole('textbox', { name: 'Type your message here...' }).click();
  await page.getByRole('textbox', { name: 'Type your message here...' }).fill('e are learning');
  await page.getByRole('textbox', { name: 'Type your message here...' }).click();
  await page.getByRole('textbox', { name: 'Type your message here...' }).fill('e are learningw');
  await page.getByRole('textbox', { name: 'Type your message here...' }).click();
  await page.getByRole('textbox', { name: 'Type your message here...' }).fill('we are learning');
  await page.getByRole('searchbox', { name: 'Search products...' }).click();
  await page.getByRole('searchbox', { name: 'Search products...' }).fill('chair');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('Playwright Logo').click();
  await page.getByRole('link', { name: 'Home', description: 'Home page link' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByTestId('edit-profile-btn').click();
  await page.getByTestId('nav-contact').getByRole('link', { name: 'Contact' }).click();
});